### ISSUE TITLE
Find top 10 players twitter handlers over 5 years

### ISSUE THREAD

**Issue by darkhark** [darkhark/NBATwitterCorrelation#13]
Instead of writing a method to determine the top scorers over the past 5 seasons, just look up the top 10 players for seasons 2016 - 2020 on nba.com. 

Once those players are discovered, locate their twitter handles, create a python file named TwitterHandles.py, and save all those names into that file as either an Enum or something else that is easily accessible for other files.

**Comment by darkhark** [comment]
The idea is that we'll be able to do something like NBAPlayer(TwitterHandles.lebron_james). I think this should allow me to get both the player name and the twitter handle if it's an Enum. It has been awhile awhile since I used an Enum though...
If it's an Enum, I believe it will also allow us to iterator through all possible values. So when we want all the players, we'll be able to create something like:
```python
players = []
for handle in TwitterHandles:
    players.append(NBAPlayer(handle))
```

**Comment by el-grudge** [comment]
i already have a json file with the twitter handles, can we use that?

**Comment by el-grudge** [comment]
i've uploaded the file to the google drive. here's a link for it 

https://drive.google.com/file/d/1mYlngtX4pMXZMhbUTWybq_DREeLzS6Ji/view?usp=sharing

**Comment by el-grudge** [comment]
you can get load the file in a dictionary

`import json`

`with open('twitter_handles.json') as json_file:`
    `twitter_handles = json.load(json_file)`

the key being the player's name as spelled on nba.stats, the value is his twitter handle

**Comment by el-grudge** [comment]
these are the top 15 players per season, for the past 5 seasons

**Comment by darkhark** [comment]
Yeah, that works too! Can you just add the JSON file to docs? Maybe make a new data directory under there, then add the JSON to that. 
Then can you add the code you have in here to main? Probably above the Instantiate players comment.

**Comment by el-grudge** [comment]
i have made the necessary changes under a local branch iss13, which i then merged to the main branch. i then tried to push that here for review, but i got the following error:  

! [remote rejected] main -> main (protected branch hook declined)

i think you need to permit changes to the main file so i can push the code here
