### ISSUE TITLE
Load player tweets from twitter

### ISSUE THREAD

**Issue by darkhark** [darkhark/NBATwitterCorrelation#2]
Use https://rapidapi.com/blog/how-to-use-the-twitter-api-with-python/ for obtaining player tweets during the NBA season. One player should be fine for now.

The python files should be written under src/main/python/loaders. Multiple python files will likely be needed to accomplish this task.

See https://github.com/darkhark/NBATwitterCorrelation/pull/3 for how I allowed different players info to be pulled in the future.

**Comment by el-grudge** [comment]
new branch created successfully. no code added yet.

**Comment by el-grudge** [comment]
new function getPlayerTweets created. Given a twitter handle, and from/to dates, the function will return a dict object, with the tweet id as key, and a Tweet object as value
