### ISSUE TITLE
Clean data retrieved from NBADataLoader

### ISSUE THREAD

**Issue by darkhark** [darkhark/NBATwitterCorrelation#4]
Not all of the columns in the dataframe will be required for the analysis. 

Removed both redundant and unneeded columns. The cleanser could probably be used as a step within the getPlayerSeasonalBoxData() method of NBADataLoader.

**Comment by afandino** [comment]
We can probably get rid of VIDEO_AVAILABLE but I compile a glossary of the stats

COLUMN_NAME | DEFINITION | NOTES
-- | -- | --
GP | Games Played |  
MIN | Minutes Played |  
FGM | Field Goals Made |  
FGA | Field Goals Attempted |  
FG_PCT | Field Goal Percentage |  
3PM | 3 Point Field Goals Made |  
3PA | 3 Point Field Goals Attempted |  
FG3_PCT | 3 Point Field Goals Percentage |  
FTM | Free Throws Made |  
FTA | Free Throws Attempted |  
FT_PCT | Free Throw Percentage |  
OREB | Offensive Rebounds |  
DREB | Defensive Rebounds |  
REB | Rebounds |  
AST | Assists |  
TOV | Turnovers |  
STL | Steals |  
BLK | Blocks |  
PF | Personal Fouls |  
DD2 | Double Doubles | When a player reaches   double figures (10 or more) in two of the five main statistical categories –   points, rebounds, assists, steals and blocks
TD3 | Trible Doubles | a score in a basketball   game of at least ten points, ten rebounds, and ten assists by a single player
PTS | Points |  
+/- | Plus Minus | the plus/minus statistic is a measure of the   point differential when players are in and out of a game. It is calculated by   taking the difference in the score when the player enters the game and   subtracting it from the score when the player exits the game.
SEASON_ID |   |  
Player_ID |   |  
Game_ID |   |  
GAME_DATE |   |  
MATCHUP |   |  
WL |   |  
VIDEO_AVAILABLE |   |

**Comment by darkhark** [comment]
@el-grudge I don't follow basketball as much, but here's my idea of the stats to remove.

- GP
- MIN
- DD2
- TD3
- SEASON_ID
- Player_ID
- Game_ID
- MATCHUP
- VIDEO_AVAILABLE

What do you think?

**Comment by el-grudge** [comment]
@darkhark yes, these could be dropped. Eventually, we will need only one stat as a target variable (for example PTS), we can either drop the other stats altogether, or use them as additional predictive variable. Personally, I believe we should opt for the former, for two reasons: 1) We're testing for the sentiments predictive power, 2) More features mean a more complex model, and potentially a more biased model

**Comment by darkhark** [comment]
@el-grudge  @afandino I think the best way to handle it would be to allow flexibility. The method used to clean the data should return all point related stats (FGM through FT_PCT). These stats will be stored in the NBAPlayer object, and referenced as needed later.

When we get to writing the models, the methods in the model files will specify which stats they want (or iterate through the dict of stats) from the NBAPalyer. We can start by only using the points stat, and include more as we go in the future if able to.

**Comment by darkhark** [comment]
@afandino have you had a chance to clean it this way?

**Comment by darkhark** [comment]
Based on our discussion earlier today...
The final stats should look like the following for each game:

date: str or datetime,
pointsScored: int,
shotAccuracy: double

pointsScored will just be PTS (I think) and shotAccuracy will be (FGA + 3PA + FTA) / (FGM + 3PM + FTM) per game.

I think this will be good to return as a dataframe. The dataframe created from the cleanse here will be used saved in the NBAPlayer object.

I'm thinking all the NBAPlayer object should need to call is something like NBADataCleanser.clean(dfFromDataLoader). So NBADataCleanser probably does not need contain a class. I don't really see the need to create an object just to call a static method. I think it makes more since to just import this file and be able to use the method(s) within it.

**Comment by darkhark** [comment]
Please convert date to datetime if it is a String. It is a datetime datatype when it comes in from Twitter.
